CREATE TABLE [dbo].[TBCONDUTOR]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[Nome] VARCHAR(50) NOT NULL,
	[CNH] VARCHAR(20) NOT NULL,
	[VencimentoCnh] DATE NOT NULL,
	[CPF] VARCHAR(20) NOT NULL,
	[RG] VARCHAR(20) NOT NULL,
)
