CREATE TABLE [dbo].[TBLOCACAO]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Id_Veiculo] INT NOT NULL,
	[Id_Cliente] INT NOT NULL,
	[Plano] VARCHAR(20) NOT NULL,
	[DataSaida] DATE NOT NULL,
	[DataDevolucao] DATE NOT NULL,
	[Caucao] FLOAT NOT NULL,
	CONSTRAINT [PK_TBCLIENTE_ID] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_TBLOCACAO_TBVEICULO] FOREIGN KEY ([Id_Veiculo]) REFERENCES [dbo].[TBVEICULO]([Id]),
	CONSTRAINT [FK_TBLOCACAO_TBCLIENTE] FOREIGN KEY ([Id_Cliente]) REFERENCES [dbo].[TBCLIENTE]([Id])
)
