CREATE TABLE [dbo].[TBTAXASSERVICOS_USADOS]
(
	[Id] INT IDENTITY (1, 1) NOT NULL,
	[Id_TaxasServicos] INT NOT NULL,
	[Id_Locacao] INT NOT NULL,
	CONSTRAINT [FK_TBTAXASSERVICOS_USADOS_ID] PRIMARY KEY CLUSTERED ([Id] ASC),
	CONSTRAINT [FK_TBTAXASSERVICOS_USADOS_TBTAXASSERVICOS] FOREIGN KEY ([Id_TaxasServicos])
		REFERENCES dbo.[TBTAXASSERVICOS] ([Id]) ON DELETE CASCADE,
	CONSTRAINT [FK_TBTAXASSERVICOS_USADOS_TBLOCACAO] FOREIGN KEY ([Id_Locacao])
		REFERENCES dbo.[TBLOCACAO] ([Id]) ON DELETE CASCADE
)
